=== brtl-fhc/lolxml-common/src/main/resources/lolxml.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://lolxml.org"
	xmlns:lol="http://lolxml.org" elementFormDefault="qualified">

	<!-- Support lookup data. Not optional anymore, it inits XPath evaluator.
		Can be empty, though. -->
	<complexType name="dataType">
		<sequence>
			<any namespace="##any" processContents="lax" minOccurs="0" maxOccurs="unbounded"/>
		</sequence>
	</complexType>
	
	<!-- Template for mixed element (right term of production)  -->

	<complexType name="rightElement" mixed="true">
		<sequence minOccurs="0" maxOccurs="unbounded">
			<choice>
				<element name="exp" type="lol:expType"/>
				<element name="switch" type="lol:switchType" />
				<element name="eval" type="lol:evalType" />
				<element name="store" type="lol:storeType" />
				<element name="foreach" type="lol:foreachType" />
				<element name="if" type="lol:ifType" />
				<element name="while" type="lol:whileType" />
				<any namespace="##other" processContents="lax"/>
				<any namespace="##local" processContents="lax"/>
			</choice>
		</sequence>
	</complexType>


	<!-- Non-terminal symbol. Evaluates its content when referenced. -->
	<complexType name="symType">
		<complexContent>
			<extension base="lol:rightElement">
				<attribute name="id" use="required" type="ID" />
			</extension>
		</complexContent>
	</complexType>


	<!-- Random chooser for production rules. -->
	<complexType name="switchType">
		<sequence>
			<element name="case" minOccurs="1" maxOccurs="unbounded"
				type="lol:rightElement" />
		</sequence>
	</complexType>

	<!-- Iterate through nodeset specified by inline XPath (select), referenced
	 	Exp (idref) or stored in property (property), and evaluate content.
	 	Exposes active node as property (name declared in "var" attribute). -->
	<complexType name="foreachType">
		<complexContent>
			<extension base="lol:rightElement">
				<attribute name="idref" type="IDREF" />
				<attribute name="select" type="string" />
				<attribute name="property" type="NMTOKEN" />
				<attribute name="var" type="NMTOKEN" />
			</extension>
		</complexContent>
	</complexType>

	
	<!-- Conditional evaluator specified by inline boolean XPath (test), 
	referenced boolean Exp (idref) or stored in property (property). -->
	<complexType name="ifType">
		<complexContent>
			<extension base="lol:rightElement">
				<attribute name="idref" type="IDREF" />
				<attribute name="test" type="string" />
				<attribute name="property" type="NMTOKEN" />
			</extension>
		</complexContent>
	</complexType>
	
	<!-- Conditional loop specified by inline boolean XPath (test), 
	referenced boolean Exp (idref) or stored in property (property). -->

	<complexType name="whileType">
		<complexContent>
			<extension base="lol:rightElement">
				<attribute name="idref" type="IDREF" />
				<attribute name="test" type="string" />
				<attribute name="property" type="NMTOKEN" />
			</extension>
		</complexContent>
	</complexType>
	
	<!-- Evaluation: references symbols, expressions and properties-->
	<complexType name="evalType">
		<attribute name="idref" type="IDREF" />
		<attribute name="property" type="NMTOKEN" />
	</complexType>
	
	<!-- Evaluates XPath expression in @value (using data element as context).
	-->
	<complexType name="expType">
		<complexContent>
			<extension base="lol:rightElement">
				<attribute name="id" type="ID" />
				<attribute name="value" type="normalizedString" use="required" />
			</extension>
		</complexContent>
	</complexType>

	<simpleType name="expTypes">
		<restriction base="string">
			<enumeration value="string"/>
			<enumeration value="boolean"/>
			<enumeration value="node"/>
			<enumeration value="nodeset"/>
			<enumeration value="number"/>
		</restriction>
	</simpleType>
	
	<!-- Store the result of either an inline XPath (if select + type are present),
		a referenced Exp/Sym (if idref is present), or nested content, 
		into a document property. Properties are global, and can 
		be overwritten. -->
	<complexType name="storeType">
		<complexContent>
			<extension base="lol:rightElement">
				<attribute name="property" type="NMTOKEN" use="required" />
				<attribute name="idref" type="IDREF" />
				<attribute name="select" type="string" />
				<attribute name="type" type="lol:expTypes" default="string" />
			</extension>
		</complexContent>
	</complexType>
	
	<!-- Root element. Grammar= data*, sym+, var*, eval -->
	<element name="grammar">
		<complexType>
			<sequence>
				<element name="data" type="lol:dataType" />
				<element name="exp" type="lol:expType" minOccurs="0" maxOccurs="unbounded" />
				<element name="sym" type="lol:symType" minOccurs="1" maxOccurs="unbounded" />
				<element name="eval" type="lol:evalType" maxOccurs="1" minOccurs="1"/>
			</sequence>
		</complexType>
	</element>

</schema>

=== brtl-fhc/lolxml-common/src/test/resources/if-test.xml
<?xml version="1.0" encoding="UTF-8"?>
<grammar xmlns="http://lolxml.org" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://lolxml.org ../../main/resources/lolxml.xsd ">

  <data>
      <farm xmlns="">
      	<animal name="chick"><sound>chick</sound></animal>
      	<animal name="pig"><sound>oink</sound></animal>
      </farm>
  </data>

  <exp id="startsWithVowel" value="contains('aeiouAEIOU',substring($animalSound,1,1))"/>
    
  <sym id="ROOT">
    <foreach select="farm/animal" var="animal">
	    <store property="animalSound" select="$animal/sound"/>
	    <store property="soundWithVowel" idref="startsWithVowel" type="boolean"/>
	    <store property="sound.x2"><eval property="animalSound"/>-<eval property="animalSound"/></store>
	    Old MacDonald had a farm, E-I-E-I-O,
	    And on that farm he had a <exp value="$animal/@name"/>, E-I-E-I-O,
	    With a<if test="$soundWithVowel">n</if> <eval property="sound.x2"/> here and a<if property="soundWithVowel">n</if> <eval property="sound.x2"/> there
	    Here a<if idref="startsWithVowel">n</if> <eval property="animalSound"/>, there a<if property="soundWithVowel">n</if> <eval property="animalSound"/>, everywhere a<if idref="startsWithVowel">n</if> <eval property="sound.x2"/>
	    Old MacDonald had a farm, E-I-E-I-O.
    </foreach> 
  </sym>
      
  <eval idref="ROOT"/>

</grammar>

=== brtl-fhc/lolxml-common/examples/bottles.xml
<?xml version="1.0" encoding="UTF-8"?>
<lol:grammar xmlns:lol="http://lolxml.org"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://lolxml.org ../src/main/resources/lolxml.xsd ">

    <!-- Programming demo from: 									-->
    <!--						http://www.99-bottles-of-beer.net/	-->
    
    
	<lol:data>
	    <start>99</start>
	</lol:data>

	<lol:sym id="VERSES">
		<lol:exp value="$bottles"/> bottles of beer on the wall, <lol:exp value="$bottles"/> bottles of beer.
		Take one down and pass it around, <lol:exp value="$bottles - 1"/> bottles of beer on the wall.
		<lol:store property="bottles" select="$bottles - 1" type="number" />
		<lol:if test="$bottles > 2"><lol:eval idref="VERSES"/></lol:if></lol:sym>
	
	<lol:sym id="SONG">
		<lol:eval idref="VERSES"/>
		2 bottles of beer on the wall, 2 bottles of beer.
		Take one down and pass it around, 1 bottle of beer on the wall.


		1 bottle of beer on the wall, 1 bottle of beer.
		Take one down and pass it around, no more bottles of beer on the wall.


		No more bottles of beer on the wall, no more bottles of beer.
		Go to the store and buy some more, 99 bottles of beer on the wall.
	</lol:sym>
		
	<lol:sym id="ROOT">
	    <lol:store property="bottles" type="number" select="start"/>
	    <lol:eval idref="SONG"/>
	</lol:sym>
	
	<lol:eval idref="ROOT"/>
	
</lol:grammar>

=== brtl-fhc/lolxml-common/src/test/resources/whitespace-test.xml
<?xml version="1.0" encoding="UTF-8"?>
<lol:grammar xmlns:lol="http://lolxml.org"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://lolxml.org ../../main/resources/lolxml.xsd ">
	
	<lol:data />

	<lol:sym id="TEXT">
		Hello
		<lol:switch>
			<lol:case>cruel</lol:case>
			<lol:case></lol:case>
		</lol:switch>
		World!
	</lol:sym>

	<lol:sym id="ROOT">
	    <lol:store property="raw" idref="TEXT"/>
	    <lol:exp value="normalize-space($raw)"/>
	</lol:sym>
	
	<lol:eval idref="ROOT" />

</lol:grammar>

=== brtl-fhc/lolxml-common/src/test/resources/func-test.xml
<?xml version="1.0" encoding="UTF-8"?>
<lol:grammar xmlns:lol="http://lolxml.org"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://lolxml.org ../../main/resources/lolxml.xsd ">

	<lol:data>
		<name>foo</name>
		<name>bar</name>
		<name>baz</name>
	</lol:data>

	<lol:sym id="ROOT">
	    random() = <lol:exp value="fn:random()"/>    	    
	    random() = <lol:exp value="fn:random()"/>    	    
	    random() = <lol:exp value="fn:random()"/>    	    
	    
	    random(10) = <lol:exp value="fn:random(10)"/>
	    random(10) = <lol:exp value="fn:random(10)"/>
	    random(10) = <lol:exp value="fn:random(10)"/>
	        
	    random(name) = <lol:exp value="fn:random(name)"/>
	    random(name) = <lol:exp value="fn:random(name)"/>
	    random(name) = <lol:exp value="fn:random(name)"/>    	    
	</lol:sym>

	<lol:eval idref="ROOT" />
</lol:grammar>

=== brtl-fhc/lolxml-common/src/test/resources/exp-test.xml
<?xml version="1.0" encoding="UTF-8"?>
<grammar xmlns="http://lolxml.org" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://lolxml.org ../../main/resources/lolxml.xsd ">

  <data>
      <farm xmlns="">
      	<animal name="duck"><sound>quack</sound></animal>
      	<animal name="cow"><sound>moo</sound></animal>
      </farm>
  </data>
  
  
  <sym id="animalName"><switch>
      <case>duck</case>
      <case>cow</case></switch></sym>
      
  <sym id="root">
    <store property="animalName"><eval idref="animalName"/></store>
    <exp id="animalSound" value="farm/animal[@name=$animalName]/sound" />    
    <store property="sound.x2"><eval idref="animalSound"/>-<eval idref="animalSound"/></store>
    Old MacDonald had a farm, E-I-E-I-O,
    And on that farm he had a <eval property="animalName"/>, E-I-E-I-O,
    With a <eval property="sound.x2"/> here and a <eval property="sound.x2"/> there
    Here a <eval idref="animalSound"/>, there a <eval idref="animalSound"/>, everywhere a <eval property="sound.x2"/>
    Old MacDonald had a farm, E-I-E-I-O. 
  </sym>
      
  <eval idref="root"/>

</grammar>

=== brtl-fhc/lolxml-common/src/test/resources/exp-node-test.xml
<?xml version="1.0" encoding="UTF-8"?>
<grammar xmlns="http://lolxml.org" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://lolxml.org ../../main/resources/lolxml.xsd ">

  <data>
      <farm xmlns="">
      	<animal name="duck"><sound>quack</sound></animal>
      	<animal name="cow"><sound>moo</sound></animal>
      </farm>
  </data>
  
  <exp id="selectAnimal" value="farm/animal[@name=$animalName]"/>
  
  <sym id="NAME"><switch>
      <case>duck</case>
      <case>cow</case></switch></sym>
      
  <sym id="ROOT">
    <store property="animalName" idref="NAME" />
    <store property="animal" idRef="selectAnimal" type="node"/>
    <store property="sound"><exp value="$animal/sound"/></store>
    <store property="sound.x2"><exp value="concat($sound,'-',$sound)" /></store>
    Old MacDonald had a farm, E-I-E-I-O,
    And on that farm he had a <eval property="animalName"/>, E-I-E-I-O,
    With a <eval property="sound.x2"/> here and a <eval property="sound.x2"/> there
    Here a <eval property="sound"/>, there a <eval property="sound"/>, everywhere a <eval property="sound.x2"/>
    Old MacDonald had a farm, E-I-E-I-O. 
  </sym>
      
  <eval idref="ROOT"/>

</grammar>

=== brtl-fhc/lolxml-common/src/test/resources/func-evaluate-test.xml
<?xml version="1.0" encoding="UTF-8"?>
<lol:grammar xmlns:lol="http://lolxml.org"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://lolxml.org ../../main/resources/lolxml.xsd ">

    <!-- Node evaluation from XPath expression. -->
    
	<lol:data>
		<ref>WORLD</ref>	
	</lol:data>

	<lol:sym id="WORLD">World</lol:sym>
	
	<lol:sym id="HELLO"><lol:exp value="'Hello'"/></lol:sym>

	<lol:sym id="ROOT">
	    <lol:exp value="lol:evaluate('HELLO')"/> <lol:exp value="lol:evaluate(ref)"/>
	</lol:sym>

	<lol:eval idref="ROOT" />
</lol:grammar>

=== brtl-fhc/lolxml-common/src/test/resources/while-test.xml
<?xml version="1.0" encoding="UTF-8"?>
<grammar xmlns="http://lolxml.org" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://lolxml.org ../../main/resources/lolxml.xsd ">
  
  <data />
  
  <exp id="tableInRange" value="$i &lt;= 9"/>
  
  <sym id="ROOT">
      <store property="i" type="number" select="1"/>
      <while idref="tableInRange">
          <store property="j" type="number" select="1"/>
	      <while test="$j &lt; 11">
	          <exp value="$i"/> x <exp value="$j"/> = <exp value="$i * $j"/>
			  <store property="j" type="number" select="$j+1" />
	      </while>
	      <store property="i" type="number" select="$i+1" />	   
	  </while>
  </sym>
      
  <eval idref="ROOT"/>

</grammar>
